### ISSUE TITLE
Example of custom filter JS file? 

### ISSUE THREAD

**Issue by paulmsmith** [devoptix/wintersmith-nunjucka#1]
Hi,

I don't suppose you can provide an example of a custom filter? Something really quick and basic, whatever is passed will get "blah!" appended to it. 

Thanks. :)

**Comment by waynebloss** [comment]
There are 2 ways to configure custom filters.

One way is to specify "filterfile": "path-to-filters-file.js" in your "nunjucks" wintersmith config. Like this:

```javascript
"nunjucks": {  
    "filterfile": "nunjucks.filters.js"
}
```
Then create that file with something like the following contents:
```javascript
// Contents of nunjucks.filters.js

function or(str, defaultValue) {
  return str || defaultValue;
}
exports.or = or;

exports.other = function(str, defaultValue) { return "something else"; };

// ... This is basically just a normal Node.js module that exports functions,
// however the functions all follow the Nunjucks filter function declaration style.
```

The other way is to configure "nunjucks" like this:

```javascript
"nunjucks": {  
    "filterdir": "filters",
    "filters": ["myfirstfilter"]
}
```
and then you have to create a directory called "filters" and put one file per function in that directory. Each file should look something like this:

```javascript
module.exports = function(str, opt) {
  return "my filter functionality...";
}
```

**Comment by waynebloss** [comment]
One other note - you can mix both modes of filter configuration and they should all work.

I will update the readme with this information ASAP. Thank you.

**Comment by paulmsmith** [comment]
Hey thanks for that. Worth adding to the docs. I was missing ```module.exports```. Still new to Node land. Not having to create a new file for each filter is the way I'll go. Thanks again!
